version: '3.5'

services:
  postgres:
    container_name: postgres_db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'postgres_db'
      POSTGRES_USER: 'ecommerce'
      POSTGRES_PASSWORD: 'ecommerce'
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    expose:
      - '3306'
    # networks:
    #   - postgres

# Names our volume
volumes:
  postgres:
